Return-Path: <linux-can-owner@vger.kernel.org>
X-Original-To: lists+linux-can@lfdr.de
Delivered-To: lists+linux-can@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id B88C66D652C
	for <lists+linux-can@lfdr.de>; Tue,  4 Apr 2023 16:23:55 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S235822AbjDDOXx (ORCPT <rfc822;lists+linux-can@lfdr.de>);
        Tue, 4 Apr 2023 10:23:53 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:53572 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S235230AbjDDOXx (ORCPT
        <rfc822;linux-can@vger.kernel.org>); Tue, 4 Apr 2023 10:23:53 -0400
Received: from mail-io1-f71.google.com (mail-io1-f71.google.com [209.85.166.71])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id B4D641734
        for <linux-can@vger.kernel.org>; Tue,  4 Apr 2023 07:23:51 -0700 (PDT)
Received: by mail-io1-f71.google.com with SMTP id j4-20020a6b5504000000b00758646159fbso20237216iob.20
        for <linux-can@vger.kernel.org>; Tue, 04 Apr 2023 07:23:51 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20210112; t=1680618231; x=1683210231;
        h=to:from:subject:message-id:date:mime-version:x-gm-message-state
         :from:to:cc:subject:date:message-id:reply-to;
        bh=3SlLCphVS7COIvWP0KM6YgJ3hMpNmeYt4UE66TAXhBg=;
        b=O8IcW5GLzyIgK2HBlf8mR1lWj1eAn7qK3jJZu8jNHXetj6SlW2ItTIvZmXZb1JPFC2
         CSporG3nuPhCrhlaH9xx6jFA7fLfJVg+btYTZdrmnCNpB67H3L3cz/odaZhrbaeZjcsg
         Agajrxo+JSyqp6TDt0DqXZyxekNvBAsBnJ0xan+RoJNMOkR+swWGkGiEB+DTIF5i2BaT
         XMLNyukATUsEmkF/lHyhhU+sFGqJNDNhvYgHwTI1xR2Ump7/gRqaBYUrcdYp/Gns/r+F
         +YZ+FqxLFGWilBnvv2Qxp8hVrNIXjfJT2kGjPc8kgT3cjO+oSTJV0uaHA/4hzMD8ivRB
         Fb8A==
X-Gm-Message-State: AAQBX9fty8OKA4nPiZNUNCLd57wSeXnm7ndhjbkGGQFsEldMDMT5Ss3L
        Smd6E7jbVoH26icLOf9i+LPQ+LvsEUdYUwRoVl3gl4fu9LnqvUQ=
X-Google-Smtp-Source: AKy350Z0mNNXT0EuW2xsOe+fbbOokf0xsR7PvAWET2NX2Ap9gCGDKbW7Ov0uRnJHREoKUMl/Ribj4Ux8NNaCk0LzFXekHJRl+9Rj
MIME-Version: 1.0
X-Received: by 2002:a05:6e02:b21:b0:326:1bf1:234 with SMTP id
 e1-20020a056e020b2100b003261bf10234mr1696371ilu.3.1680618231103; Tue, 04 Apr
 2023 07:23:51 -0700 (PDT)
Date:   Tue, 04 Apr 2023 07:23:51 -0700
X-Google-Appengine-App-Id: s~syzkaller
X-Google-Appengine-App-Id-Alias: syzkaller
Message-ID: <000000000000ab085f05f8836ccd@google.com>
Subject: [syzbot] Monthly can report
From:   syzbot <syzbot+list4d04fa20a60bb21c56c5@syzkaller.appspotmail.com>
To:     linux-can@vger.kernel.org, linux-kernel@vger.kernel.org,
        mkl@pengutronix.de, netdev@vger.kernel.org,
        syzkaller-bugs@googlegroups.com
Content-Type: text/plain; charset="UTF-8"
X-Spam-Status: No, score=0.6 required=5.0 tests=FROM_LOCAL_HEX,
        HEADER_FROM_DIFFERENT_DOMAINS,RCVD_IN_DNSWL_NONE,RCVD_IN_MSPIKE_H2,
        SPF_HELO_NONE,SPF_PASS autolearn=no autolearn_force=no version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <linux-can.vger.kernel.org>
X-Mailing-List: linux-can@vger.kernel.org

Hello can maintainers/developers,

This is a 30-day syzbot report for the can subsystem.
All related reports/information can be found at:
https://syzkaller.appspot.com/upstream/s/can

During the period, 0 new issues were detected and 1 were fixed.
In total, 16 issues are still open and 39 have been fixed so far.

Some of the still happening issues:

Crashes Repro Title
1783    Yes   WARNING in j1939_session_deactivate
              https://syzkaller.appspot.com/bug?extid=535e5aae63c0d0433473
502     Yes   WARNING in j1939_session_deactivate_activate_next
              https://syzkaller.appspot.com/bug?extid=3d2eaacbc2b94537c6c5
277     Yes   possible deadlock in j1939_sk_queue_drop_all
              https://syzkaller.appspot.com/bug?extid=3bd970a1887812621b4c
55      No    possible deadlock in j1939_session_activate
              https://syzkaller.appspot.com/bug?extid=f32cbede7fd867ce0d56

---
This report is generated by a bot. It may contain errors.
See https://goo.gl/tpsmEJ for more information about syzbot.
syzbot engineers can be reached at syzkaller@googlegroups.com.
